version: '3'
services:
  mysql-server:
    command: --default-authentication-plugin=mysql_native_password
    build: mysql_container/
    ports:
      - "9999:3306"
  nginx-server:
    build: nginx_php_fpm_container/
    ports:
      - "9998:80"
  adminer:
    image: adminer
    ports:
      - 9997:8080
