version: '3'
services:
  nginx-server:
    build: nginx_php_service/
    ports:
      - "9000:80"
    volumes:
      - ./nginx_php_service/html:/app
  mysql-server:
    command: --default-authentication-plugin=mysql_native_password
    build: mysql_service/
    ports:
      - "9001:3306"
  users-management-service:
    build: users_management_service
    ports:
      - "9002:4567"
  adminer:
    image: adminer
    ports:
      - 9999:8080
