version: '3'
services:
  web-service:
    build: web_service/
    ports:
      - "9000:80"
    volumes:
      - ./web_service/html:/app
  db-service:
    command: --default-authentication-plugin=mysql_native_password
    build: db_service/
    ports:
      - "9001:3306"
  users-service:
    build: java_microservices/users_service
    ports:
      - "9002:4567"
  adminer:
    image: adminer
    ports:
      - 9999:8080
